### ISSUE TITLE
Add Google Contact data source

### ISSUE THREAD

**Issue by samber** [mholt/timeliner#12]

**Comment by mholt** [comment]
This is an interesting idea... although I'm not sure what from Google Contacts would constitute an "item" since "people" don't really fall into a timeline. However, the timeline database does have a couple of tables for people, and relating people to items/accounts... so I dunno, maybe we could find a way to add just people and not items... 🤔

**Comment by mholt** [comment]
I don't think people belong as items on a timeline; so, closing this in favor of a different idea to map people to items.
