### ISSUE TITLE
[Suggestion] Change metadata datatype in database from blob so some readable format

### ISSUE THREAD

**Issue by hstolte** [mholt/timeliner#19]
Currently, the metadata is stored as a blob in the database and it's not straightforward to read and parse from within SQL or other programming languages.

I would suggest to store the metadata in separate tables, but I am not sure what a good design would be for that. 

A short-term solution could be to store it as serialized text (e.g. json).

What do you think?

**Comment by mholt** [comment]
I chose gob encoding (with the type information stripped from the beginning) because it is highly compact / efficient. JSON is the opposite. (I have a blog post coming up about how trimming the type info from the beginning of these gobs saves like 1400% space or something, because non-empty values on metadata will be very sparse.)

I realize gob isn't used outside of Go, but it's a very well-documented format, and actually somewhat simple to do basic decoding: https://golang.org/pkg/encoding/gob/

I think I'd like to leave it as-is for now.

**Comment by hstolte** [comment]
Alright. Thanks for the answer. I'll close this for now.
