### ISSUE TITLE
add support for azure blobs for files

### ISSUE THREAD

**Issue by prabirshrestha** [mholt/timeliner#30]

**Comment by mholt** [comment]
Can you explain more what you mean?

**Comment by prabirshrestha** [comment]
Instead of saving videos and photos to file system. I would like it to run in the cloud and save it to azure blob.

**Comment by mholt** [comment]
I see, thanks for the explanation.

So.... I hate to do this to all 3 issues you just opened, but I'm gonna close them, because... the point of Timeliner is to have your data on your _own_, local computer. Not in the cloud. The point is to get the data out of the cloud. So I don't think these features are in-line with the goals of the project.

**Comment by prabirshrestha** [comment]
Makes sense. Thanks for the quick response.
