### ISSUE TITLE
Event Stream

### ISSUE THREAD

**Issue by joeblew99** [mholt/timeliner#32]
Can this notify you when a data sources data has changed ?
For example when you added a new google photo. Or if you edited it or deleted it.
Its basically an Event Stream.
Alot liek CDC. https://en.wikipedia.org/wiki/Change_data_capture

Not all Data sources would support this i am guessing.

Anyway then the system would be able to see the event and then go get the blob if it wanted to.

just an idea.

**Comment by mholt** [comment]
Hmm, not with most data sources, which would need to have some sort of streaming API (either that, or we'd have to do frequent polling, which is expensive). I suppose it could in theory report how many items were added or removed after an operation, but that's not a live event stream. I don't think it's really feasible/possible unless most data sources supported something like that with their APIs, which seems unlikely, incentive-wise. That's why we just run it on a schedule right now, it's like very infrequent polling.
